name: Python Unittest

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install unittest-xml-reporting

      - name: Run unittest tests
        run: |
          mkdir -p test-results
          python -m unittest discover -s src
#          python -m xmlrunner discover -s src -p "test_*.py" -o test-results

#      - name: Upload test results
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: unittest-results
#          path: test-results/
#          retention-days: 14